# Generated by Django 3.0.1 on 2020-01-03 07:59

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr, MultiPolygon, Polygon
from pathlib import Path

DATA_FILENAME = 'schools/migrations/residential_area_data.json'


def load_data(apps, schema_editor):
    residential_area = apps.get_model('schools', 'ResidentialArea')
    json_file = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(json_file)) as datafile:
        objects = json.load(datafile)
        for obj in objects['features']:
            try:
                obj_type = obj['geometry']['type']
                properties = obj['properties']
                obj_geometry = obj['geometry']
                name = properties.get('mvt_id', 'no-name')
                coordinates = obj_geometry.get('coordinates', [])
                if obj_type == 'Polygon':

                    location = MultiPolygon(Polygon(coordinates[0]), srid=4326)
                    residential_area(name=name, location=location).save()
                elif obj_type == 'MultiPolygon':
                    location = MultiPolygon(Polygon(coordinates[0][0]), srid=4326)
                    residential_area(name=name, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0003_residentialarea'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
