# Generated by Django 3.0.1 on 2020-01-05 04:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200103_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialarea',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
    ]
